### ISSUE TITLE
Part 2 of the rewrite

### ISSUE THREAD

**Issue by xaviervia** [xaviervia/washington#29]
- [x] Customizing output format in the "Output format" section, linking to examples of how it's done
- [x] Move "advanced usage" to the README of the washington.core package
- [ ] Some GIF demonstration, maybe of running a short test suite
- [ ] HTML Browser formatter. Ideally, use it to showcase washington with a live demo on the library site. Built in React I guess, it will need a target element to render.
- [ ] Finish the "Code Document" write up 
- [ ] Add examples of how to replicate the scenario lifecycle of Mocha and such in a functional way (`[...].map((case) => ({...case, test: compose(case.test, beforeEach) })`)
- [ ] Think about adding filtering, but not too hard since it can be done before passing the array of tests to Washington
- [ ] Logo

Ideas (can be ignored):

- [ ] Run through the examples from the cheat sheet in a screencast
- [ ] Would it be possible to have a Karma reporter?
- [ ] Would it be a good idea to point out that it can be used instead of Jest by wrapping the tests with JSdom?

**Comment by xaviervia** [comment]
Extract taken away from the new README:

```markdown
## A vision: the code document

Combining the simplicity

## Output format

**TODO**

## Advanced usage

**TODO** you will be able to consume the output of the tests programmatically with a `folktale` Task.
```

**Comment by xaviervia** [comment]
```markdown
> Note that the above code is not using the Washington helpers for constructing the examples. The intention is to make it transparent to you right now that the example scenarios that Washington works with are plain JavaScript objects. This opens up a [plethora of opportunities to organize your tests as it better pleases you](#a-proposal-the-code-document).
```

⬆️ to add the "code document" writeup

```markdown
But sure some of you disagree! Well, if you for some reason you really like Washington’s approach and would like to use it, but you also really want to get a nested structure of tests, remember: examples are just plain JavaScript objects. You are more than welcome to add a `namespace` or `breadcrumbs` property to them and use it in a custom formatter to organize the output of the test suite. Go ahead to the [advanced usage](#advanced-usage) section for an explanation of how to write a formatter (it’s not hard either).
```

Add the "advanced usage" section.

**Comment by xaviervia** [comment]
In here: https://github.com/xaviervia/washington#but-what-about-namespaces

Add the example:

```javascript
const addNamespace = namespace => example => 
  ({...example, description: `${namespace}: ${example.description}`})

testSuite.map(addNamespace('Addition'))
```

**Comment by xaviervia** [comment]
Add explanation about starting up with Lerna (`make` tasks) in here: https://github.com/xaviervia/washington#collaborating
